### ISSUE TITLE
urllib cannot retrieve HTTPS image

### ISSUE THREAD

**Issue by mic1780** [harmonicradius/diyScgApi#1]
Running `cut_img.py` would throw an error on line 164, `myopener.retrieve`, but by changing the request url to a normal HTTP schema I was able to fetch the image.

System info:
- MacBook Pro (OSX 10.11.5)
- Python 2.7.11
  - requests[security]
  - urllib3
  - PIL
  - BeautifulSoup4
- Node 6.2.2
- ImageMagick

**Comment by rogersnick** [comment]
thanks. changed. 
I wonder if this resulted from an SCG side change..
